---
title: "About"
---

### Revised Assignment #1:

### Revised Analyses:

1. Border Crossing Entry Data, Analysis
  - As reflected by the country border crossing data, the Mexico-America border has much more traffic than the Canada-America border. Most ports are visited between 1,000 and 2,000 times per year, with an exception of many ports in the North. New York sees a lot of border entry instances and quantity of crossing into the United States. Texas and California receive the most border entries of any other state.
  - Traffic seems to be highly concentrated on a few ports in each border state. There is heavy pedestrian and personal vehicle traffic in Texas, California and New York. States in the Midwest get virtually no traffic in comparison to the South or New York and Washington.
2. Most Popular Baby Names in New York City, Analysis
  - Emma remained the most popular name in New York City between 2017 and 2021, a much longer spot at the top than the three other names. Although Emma is the most popular, the general popularity of popular baby names has steadily declined since 2013. In 2021 over 400 babies were named Emma, but this pales in comparison to over 600 Sophias in 2013.
  - Unlike female baby names, male baby names are more consistent. Liam remained the most popular baby name for six years, from 2016 to 2021. The lowest number of babies named the most popular name was in 2020 with 676 Liams, and the highest number was in 2011 with 822 Jaydens. Male baby names are far more popular in quantity than female names.
3. Crime in Los Angeles, Analysis
  -  2024, one of the most prevalent crimes in Los Angeles was car theft, with hot spots around downtown LA, Santa Monica and Canoga Park, above Topanga State Park. Santa Monica was also a hot spot for petty and grand theft, around Venice Beach and the Los Angeles airport. Northern LA County, which includes Santa Clarita and Lancaster, is untouched in regards to top 50 areas and type of crime of 2024.

### Assignment #1:

-  *Analyze three different (simple) datasets in RStudio*
    - *Provide Quarto sites/code for each dataset to review*
    - *Create a graphic using ggplot, plotly or Datawrapper for each set (each must be a different visual style — line, bar, map etc.)*
- *For one of the previous sets, create three graphics from the same data (each a different visual style)*

### Analyses

I analyzed three different datasets from https://data.gov/.

1. Border Crossing Entry Data, Analysis
  - Texas has by far the most border traffic of any other border state with over 120 million crossings in 2024. Although California is closer behind,       there is a steep decrease in border traffic around the Canadian border and other Southern states beyond Texas and California.
  - Border traffic along the US-Mexico border almost doubled traffic along the US-Canada border. There was a peak for border traffic along the US-Mexico     border around and just before 2000, and a dramatic fall in 2020 during the COVID-19 pandemic.
  - The vast majority of border traffic is personal vehicle traffic. Pedestrian border traffic blew me away with almost 50 million pedestrians crossing     the border in 2019. Group transportation took a hit during the pandemic, with buses dropping more than half of their report in 2019, from almost        230,000 to almost 100,000 in 2020.
2. Most Popular Baby Names in New York City, Analysis
  - Esther and Isabella fought from 2018 to 2020 for the title of most popular, and Esther was, in 2021, the most popular baby name in New York City.       This being said, the amount of people naming their female babies the most popular name was on a steep decline over the ten year period.
  - On a different note, regarding male baby names, it seems to be more popular to name babies the most popular name of the year. This is a strong          comparison from almost 450 babies named Liam in 2021 and under 200 named Esther. 
3. Crime in Los Angeles, Analysis
  - The most frequent crimes in Los Angeles are non-violent, with an exception of assault and battery. As of 2024, crime in Los Angeles, on all fronts,     is declining. Interestingly, in 2022, identity theft was the second most frequent crime, with over 22,000 occurrences. Stolen vehicles have remained     at the top of the list over all four years, and it saw a slight peak of almost 25,000 occurrences, also in 2022.
  
  